# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20160919_0648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
