# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-27 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('position', models.SmallIntegerField(default=0, verbose_name='position')),
            ],
            options={
                'ordering': ('position',),
                'verbose_name': 'new category',
                'verbose_name_plural': 'new categories',
            },
        ),
        migrations.AddField(
            model_name='new',
            name='new_category',
            field=models.ManyToManyField(to='newsapp.NewCategory', verbose_name='new categories'),
        ),
    ]
